# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf552b100bfa8f399bf9992deaaf2578398f86daddc3d05cbe49ae4c1b09d7d0372d1845376e2c8d0894d821360bb5f5fb823dcdb7d114a7f985b12b5fc16e47

test:
  secret_key_base: d20deddf831ccc1e60956e5bf1bfb7810fa1f9e5b79956db41d93a622ea91daa1a03f3d3b35b848669b021f09172491b6cba8d04faf65f6b4d68ef5cc7d7bcde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
